### ISSUE TITLE
Deposit -> Target field displays (inactive up/down buttons).

### ISSUE THREAD

**Issue by timjlowe** [nahmii-community/bridge#13]
The greyed out up/down buttons on the L2 destination field are not required.

![image](https://user-images.githubusercontent.com/26362997/137290556-d8178f87-5ee8-4a16-a080-834b60e7f339.png)

**Comment by HDauven** [comment]
Oh, that's interesting. I don't have that on Chrome. You're probably running a different browser @timjlowe? 

The inputs need a refactor in general. They'll be turned into a text field (removing the buttons you mentioned) and get improved input validation. The current implementation is a bit buggy.
