### ISSUE TITLE
L2 "Balance" field and duplicate field below is slightly confusing!

### ISSUE THREAD

**Issue by timjlowe** [nahmii-community/bridge#16]
Having the Balance displayed twice suggests that there is some other functionality on this screen.
![image](https://user-images.githubusercontent.com/26362997/137292313-fbd59e22-86ca-4946-9b36-cae9f5f818ae.png)

**Comment by HDauven** [comment]
Agreed. This can be improved. I will ask around a bit about peoples opinions on this.

What do you think @timjlowe? Remove that field altogether? Maybe let it display the new value if you deposit?

**Comment by HDauven** [comment]
@timjlowe others have recommended to mirror the value. I'm not sure what would be preferable. Your suggestion makes more sense to me and adds more value for the end users.
