### ISSUE TITLE
Explorer link on withdraw toast is broken

### ISSUE THREAD

**Issue by hill399** [nahmii-community/bridge#37]
### Problem description
When a user initiates a withdraw, the toast link to redirect to the explorer is broken and 404's.

### Expected behaviour
Link should take you to the correct TX page on the explorer.

### Potential solution
`lib/bridge/Bridge.svelte @ 340` has an incorrect prefix of `/txt/` rather than `/tx/`

**Comment by HDauven** [comment]
Thank you for reporting this bug @hill399! It should be fixed now. :)
