### ISSUE TITLE
Clearing localstorage when in claim period loses ability to withdraw.

### ISSUE THREAD

**Issue by hill399** [nahmii-community/bridge#51]
**Describe the bug**
When a user initiates a withdrawal on the bridge, a record of this is stored in localstorage. Now _IF_ the user is to clear their browser storage (or use a different PC/mobile) then they will lose this record and be unable to withdraw using this method - as it appears it rely solely on this localstorage entry.

**To Reproduce**
1. Initiate withdraw on testnet. Withdraw appears on account page.
2. Clear browser storage (with localstorage erase). 
3. View account page, records are no longer visible.

**Expected behavior**
Deposits and withdrawal should be visible to the user regardless of prior localstorage records. Should be regenerated upon connecting Ethereum account.

**Possible Solution**
Implement an initial check on load to fetch contract deposits & withdrawals via contract events. This will allow for records to be regenerated and continue to be used as intended.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Ubuntu 20.04 LTS
 - Browser [e.g. chrome, safari]: Chrome v96

**Comment by HDauven** [comment]
This has been explicitly ignored to prevent large number of calls to either our JSON-RPC clients or block explorer.

An option I considered was to provide this ability as a standalone tool to prevent users from being able to "DDoS" our services or being blacklisted for executing too many actions towards our services.

The following options and changes are in consideration:
- Add a remove icon next to finalized withdrawals
- Ability for users to add in progress withdrawals to localStorage. (These should be checked against either our nGeth node or the block explorer)
- A button to automatically populate the localStorage with not yet added withdrawals. (This requires a good amount of further research in the most efficient approach)

**Comment by hill399** [comment]
I think point 2 is a nice solution for the interim, it will give users some ability to withdraw with minimum interaction (fetching the tx hash).

I'm not 100% familiar with the stack, but maybe running a private graph node and subgraph for the bridge contracts could reduce the load on the RPC interface. Would take longer to set up than traditional RPC calls, but will lay the foundations if nahmii wants to integrate into their hosted service.

`https://github.com/graphprotocol/graph-node`
